### PR TITLE
Merged with https://github.com/restify/plugins/pull/10

### PR DESCRIPTION
**Pull request by retrohacker**
Hey :smile: 

I pulled over the changes from https://github.com/restify/plugins/pull/10 to this repo. This removes the cyclic dependency on restify!

Happy to have the official CORS middleware live here. Alternatively I can create a repo under the restify org and push it there. Up to you! :heart:

### CODE REVIEW

**Comment by retrohacker** [comment]
I'd like to follow up this PR with linting if that is okay with you :smile:

**Comment by danielsarsi** [comment]
Make it happen!

**Comment by rprieto** [comment]
Sorry, only seeing this now! This is great 💯 Thanks so much for pulling this login in, that's been on our todo-list forever.

The only comment I have before merging is why values such as `access-control-request-method` have been extracted somewhere else, as I find (subjective) that it's harder to read with that level of indirection.

After it's merged, what do you think if we replace `assert-plus` with [strummer](https://github.com/TabDigital/strummer), which we typically use in `TabDigital` projects? It would make the whole "assert" block a lot more legible.

**Comment by rprieto** [comment]
@nguyenchr what do you think?

**Comment by nguyenchr** [comment]
@rprieto I agree that values like `access-control-request-method` could probably be inlined
I think it's great to have `EXPOSE_HEADERS` as an array in a common file, seeing as though it is looped over in multiple places

and yes +1 to linting (my vote is for https://standardjs.com/)

**Comment by rprieto** [comment]
:+1: on `standard`. In order to get things moving, what about we merge this now and look at simplifying later?

**Comment by retrohacker** [comment]
Also :+1: on standard fwiw :-)

**Pull request merged**
