### PR TITLE
Bump dependencies versions

### LINKED ISSUE #36: Warning on unmet peer dependency for restify
restify has released 5.0.0

As part of their migration guide, they suggest to use this library as a replacement for CORS. When I install I get a warning:

```
npm WARN restify-cors-middleware@1.0.0 requires a peer of restify@2.6.x - 4.3.x but none was installed.
```

Any risk on updating the peer dependency? I'm happy to submit a PR.

### PR DESCRIPTION
**Pull request by simonepri**
Close #36

### CODE REVIEW

**Comment by simonepri** [comment]
I can't understand why node 4 fails. (It tries to install an old version of Restify)

**Comment by simonepri** [comment]
Maybe I should split it in more PRs.

**Comment by retrohacker** [comment]
`peerDependency` defines the versions of restify this module is compatible with. That semver range should be expanded as opposed to being replaced with v5.

The devDependency should be updated to v5: https://github.com/TabDigital/restify-cors-middleware/pull/38/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L27

**Comment by simonepri** [comment]
The version 1.0.0 of the module doesn't work ONLY on v5? Is still backward compatible?

**Comment by simonepri** [comment]
Splitted to #41 and #42

**Pull request closed without merging**
