### PR TITLE
Updates restify peerDependency

### PR DESCRIPTION
**Pull request by mehdivk**
Adding support of `Restify 3.0.x`

### CODE REVIEW

**Comment by mehdivk** [comment]
@nguyenchr @rprieto Is there any reason to not update restify version range or just team didn't update it due to the fact we're using Restify 2.8? I checked changelog of Restify and looks fine and also all unit tests are green! Need this one as `api-service-metadata` will use latest version of `Restify`

**Comment by nguyenchr** [comment]
@mehdivk I don't remember if there is a reason we didn't include `Restify 3.0.x` 
@rprieto can you think of any?

also can you add a `.travis.yml` so we can get the build status

**Comment by mehdivk** [comment]
@nguyenchr `.travis.yml` came via another PR. I can see `The Travis CI build passed` in `Merge pull request` area

**Comment by rprieto** [comment]
Nice one :+1: I don't think there was a particular reason apart from the fact `v3` didn't exist yet.

Probably just worth testing locally, in case the CORS implementation has changed in Restify (since this module implements preflight, but relies on Restify for actual requests).

**Comment by wlkrw** [comment]
+1 Before I noticed this pr I was going to make one for relaxing the peer dependency. I tested with restify 3.0.2 for work, it's not on Github. How 'bout them Waratahs

**Comment by mehdivk** [comment]
@rprieto @nguyenchr @wlkrw 
I tried it with `Restify 3.0.2` and it works. Moreover last update on `cors.js` file of Restify codebase was 10 months ago and CORS feature of Restify doesn't reply on other dependencies so I think it's safe to upgrade it.

**Comment by rprieto** [comment]
Awesome, thanks Mehdi! Let's merge this :ship:

**Pull request merged**
